- README.md
- Add's build badge and description to README
> chore: add build badge and description

- .releaserc.json
- README.md
- src/BasisTheory.net.AspNetCore/BasisTheory.net.AspNetCore.csproj
- src/BasisTheory.net.Encryption.Azure.AspNetCore/BasisTheory.net.Encryption.Azure.AspNetCore.csproj
- src/BasisTheory.net/BasisTheory.net.csproj
- Adds README files to nuget package
> docs: update to package readme with Nuget package

- README.md
- src/BasisTheory.net.AcceptanceTests/Encryption/Azure/AzureKeyVaultEncryptionTests.cs
- src/BasisTheory.net.AcceptanceTests/Encryption/Azure/Helpers/AzureEncryptionController.cs
- src/BasisTheory.net.AspNetCore/BasisTheory.net.AspNetCore.csproj
- src/BasisTheory.net.AspNetCore/ServiceProviderExtensions.cs
- src/BasisTheory.net.Encryption.Azure/Factories/AesKeyVaultEncryptionFactory.cs
- src/BasisTheory.net.Tests/Tokens/Helpers/TokenFactory.cs
- src/BasisTheory.net/BasisTheory.net.csproj
- src/BasisTheory.net/Encryption/EncryptionService.cs
- src/BasisTheory.net/Encryption/Entities/EncryptedData.cs
- src/BasisTheory.net/Encryption/Extensions/EncryptedDataExtensions.cs
- src/BasisTheory.net/Tokens/Entities/EncryptionMetadata.cs
- src/BasisTheory.net/Tokens/Entities/Token.cs
- src/BasisTheory.net/Tokens/Extensions/TokenExtensions.cs
- Rename encryption data class names
> Rename encryption data

- .github/ISSUE_TEMPLATE.md
- Update Discord invitation link
> [no-ci] chore: Update Discord invite link

- .github/CODEOWNERS
- .github/workflows/pull-request.yml
> chore: update codeowners

- package.json
- src/BasisTheory.net.AcceptanceTests/BasisTheory.net.AcceptanceTests.csproj
- yarn.lock
> ENG-601 - Dependabot bumps

- .github/CODEOWNERS
- src/BasisTheory.net.Tests/Tenants/Helpers/TenantUsageReportFactory.cs
- src/BasisTheory.net/Tenants/Entities/TenantUsageReport.cs
- Adds new property to TenantUsageReport.TokenReport for `monthly_active_tokens`.
> feat: add monthly_active_tokens to TenantUsageReport

- src/BasisTheory.net.Tests/Tenants/Helpers/TenantUsageReportFactory.cs
- src/BasisTheory.net/Tenants/Entities/TenantUsageReport.cs
- Removes enrichment properties from the tenant usage report
> feat: remove enrichment properties from tenant usage report

- src/BasisTheory.net.Tests/Tenants/Helpers/TenantUsageReportFactory.cs
- src/BasisTheory.net/Tenants/Entities/TenantUsageReport.cs
- Adds included monthly active tokens field to tenant usage report
> feat: add included monthly active tokens field to tenant usage report

- src/BasisTheory.net.Tests/Logs/Helpers/LogFactory.cs
- src/BasisTheory.net/Logs/Entities/Log.cs
- Adds `actor_id` and `actor_type` to Log response object
- Removes `application_id` property which is replaced by `actor_id`
> feat: add actor_id and actor_type to Log response model

- .releaserc.json
- src/BasisTheory.net.AspNetCore/BasisTheory.net.AspNetCore.csproj
- src/BasisTheory.net.Encryption.Azure.AspNetCore/BasisTheory.net.Encryption.Azure.AspNetCore.csproj
- src/BasisTheory.net.Encryption.Azure/BasisTheory.net.Encryption.Azure.csproj
- src/BasisTheory.net/BasisTheory.net.csproj
> feat: publish assembly info

- src/BasisTheory.net.Tests/Tokens/GetTests.cs
- src/BasisTheory.net/Tokens/Requests/TokenGetRequest.cs
- Adds MetadataQuery to TokenGetRequest object to filter tokens with matching Metadata KV pairs.
> feat: add MetadataQuery to TokenGetRequest model

- src/BasisTheory.net/Tokens/Constants/TokenTypes.cs
- Adding new token types to the list
> feat: adds new token types

- src/BasisTheory.net.Tests/Tokens/SearchTests.cs
- src/BasisTheory.net/Tokens/Requests/TokenSearchRequest.cs
- src/BasisTheory.net/Tokens/TokenClient.cs
> feat: expose token search

- src/BasisTheory.net.Tests/Atomic/Banks/ReactTests.cs
- src/BasisTheory.net.Tests/Atomic/Cards/ReactTests.cs
- src/BasisTheory.net.Tests/Reactors/Helpers/ReactorFactory.cs
- src/BasisTheory.net.Tests/Reactors/ReactTests.cs
- src/BasisTheory.net/Atomic/Banks/AtomicBankClient.cs
- src/BasisTheory.net/Atomic/Cards/AtomicCardClient.cs
- src/BasisTheory.net/Reactors/ReactorClient.cs
- src/BasisTheory.net/Reactors/Requests/AtomicReactRequest.cs
- src/BasisTheory.net/Reactors/Requests/ReactRequest.cs
> feat: exposing new react endpoint

- src/BasisTheory.net.Tests/ReactorFormulas/GetTests.cs
- src/BasisTheory.net.Tests/ReactorFormulas/Helpers/ReactorFormulaFactory.cs
- src/BasisTheory.net.Tests/Reactors/GetTests.cs
- src/BasisTheory.net/ReactorFormulas/Entities/ReactorFormula.cs
- src/BasisTheory.net/ReactorFormulas/Requests/ReactorFormulaGetRequest.cs
- src/BasisTheory.net/Reactors/Requests/ReactorGetRequest.cs
- removing source token type from reactors and formulas
> feat: removing source token type

- src/BasisTheory.net.Tests/Tokens/Helpers/TokenFactory.cs
- src/BasisTheory.net/Tokens/Entities/Token.cs
- Add search_indexes to post /tokens and /tokenize, and token responses
> feat: eng 2886 add search indexes

- src/BasisTheory.net.Tests/Proxies/CreateTests.cs
- src/BasisTheory.net.Tests/Proxies/DeleteTests.cs
- src/BasisTheory.net.Tests/Proxies/GetByIdTests.cs
- src/BasisTheory.net.Tests/Proxies/GetTests.cs
- src/BasisTheory.net.Tests/Proxies/Helpers/ProxyFactory.cs
- src/BasisTheory.net.Tests/Proxies/Helpers/ProxyFixture.cs
- src/BasisTheory.net.Tests/Proxies/UpdateTests.cs
- src/BasisTheory.net.Tests/Reactors/Helpers/ReactorFactory.cs
- src/BasisTheory.net/Proxies/Entities/Proxy.cs
- src/BasisTheory.net/Proxies/ProxyClient.cs
- src/BasisTheory.net/Proxies/Requests/ProxyGetRequest.cs
Adds `/proxies` CRUD and Reactors `Application`
> feat: add proxies and reactor application

- src/BasisTheory.net.AcceptanceTests/BasisTheory.net.AcceptanceTests.csproj
- src/BasisTheory.net.Encryption.Azure.AspNetCore/BasisTheory.net.Encryption.Azure.AspNetCore.csproj
- src/BasisTheory.net.Tests/BasisTheory.net.Tests.csproj
- src/BasisTheory.net.Tests/Proxies/Helpers/ProxyFactory.cs
- src/BasisTheory.net/BasisTheory.net.csproj
- src/BasisTheory.net/Proxies/Entities/Proxy.cs
- Adds Require Authentication property to Proxy entity.
> feat: add require auth to proxy entity

- src/BasisTheory.net.Tests/Proxies/Helpers/ProxyFactory.cs
- src/BasisTheory.net/Proxies/Entities/Proxy.cs
- Adds Reactor Response to Proxy entity
> feat: add response reactor to proxy

- src/BasisTheory.net.Tests/Atomic/Banks/UpdateTests.cs
- src/BasisTheory.net.Tests/Atomic/Cards/Helpers/AtomicCardFactory.cs
- src/BasisTheory.net.Tests/Atomic/Cards/UpdateTests.cs
- src/BasisTheory.net.Tests/Tenants/Helpers/TenantFactory.cs
- src/BasisTheory.net.Tests/Tenants/UpdateTests.cs
- src/BasisTheory.net.Tests/Tokens/CreateChildTests.cs
- src/BasisTheory.net.Tests/Tokens/CreateTests.cs
- src/BasisTheory.net.Tests/Tokens/Helpers/TokenFactory.cs
- src/BasisTheory.net/Atomic/Banks/AtomicBankClient.cs
- src/BasisTheory.net/Atomic/Banks/Entities/AtomicBank.cs
- src/BasisTheory.net/Atomic/Banks/Requests/AtomicBankUpdateRequest.cs
- src/BasisTheory.net/Atomic/Cards/AtomicCardClient.cs
- src/BasisTheory.net/Atomic/Cards/Entities/AtomicCard.cs
- src/BasisTheory.net/Atomic/Cards/Requests/AtomicCardUpdateRequest.cs
- src/BasisTheory.net/Tenants/Entities/Tenant.cs
- src/BasisTheory.net/Tenants/Requests/TenantUpdateRequest.cs
- src/BasisTheory.net/Tenants/TenantClient.cs
- src/BasisTheory.net/Tokens/Entities/TokenResponse.cs
- src/BasisTheory.net/Tokens/Requests/TokenCreateRequest.cs
- src/BasisTheory.net/Tokens/TokenClient.cs
- Adds DuplicateToken option to token create request and adds settings to Tenant.
> feat: add deduplication option to token and settings to tenant

- src/BasisTheory.net.Tests/Tokens/Helpers/TokenFactory.cs
- src/BasisTheory.net.Tests/Tokens/UpdateTests.cs
- src/BasisTheory.net/Common/BaseClient.cs
- src/BasisTheory.net/Tokens/Requests/TokenUpdateRequest.cs
- src/BasisTheory.net/Tokens/TokenClient.cs
- Adds token update operation.
> feat: add token update

- src/BasisTheory.net.Tests/Tokens/Helpers/TokenFactory.cs
- src/BasisTheory.net/Tokens/Entities/Token.cs
- src/BasisTheory.net/Tokens/Requests/TokenCreateRequest.cs
- src/BasisTheory.net/Tokens/Requests/TokenUpdateRequest.cs
- Add mask to token requests and response
> feat: add mask to create/update token requests and response

- src/BasisTheory.net.Tests/Tokens/Helpers/TokenFactory.cs
- src/BasisTheory.net/Tokens/Entities/Token.cs
- src/BasisTheory.net/Tokens/Requests/TokenCreateRequest.cs
- Adds `expires_at` prop to token and token create request
> feat: add token expires_at

- src/BasisTheory.net.AcceptanceTests/BasisTheory.net.AcceptanceTests.csproj
- src/BasisTheory.net.AspNetCore/BasisTheory.net.AspNetCore.csproj
- src/BasisTheory.net.Encryption.Azure.AspNetCore/BasisTheory.net.Encryption.Azure.AspNetCore.csproj
- src/BasisTheory.net.Tests/BasisTheory.net.Tests.csproj
- src/BasisTheory.net.Tests/Tenants/Helpers/TenantUsageReportFactory.cs
- src/BasisTheory.net/BasisTheory.net.csproj
- src/BasisTheory.net/Tenants/Entities/TenantUsageReport.cs
- Adds `monthly_active_token_history` to Token Report object
> feat: add monthly_active_token_history to Token Report

- src/BasisTheory.net.Tests/Applications/CreateTests.cs
- src/BasisTheory.net.Tests/Applications/Helpers/ApplicationFactory.cs
- src/BasisTheory.net.Tests/Tokens/Helpers/TokenFactory.cs
- src/BasisTheory.net/Applications/Entities/AccessRule.cs
- src/BasisTheory.net/Applications/Entities/Application.cs
- src/BasisTheory.net/Tokens/Entities/Token.cs
- Adds support for access rules on applications
- Adds support for containers on tokens
> feat: adds support for access rules and containers

- src/BasisTheory.net.Tests/Sessions/AuthorizeTests.cs
- src/BasisTheory.net/Sessions/Requests/AuthorizeSessionRequest.cs
- src/BasisTheory.net/Sessions/SessionClient.cs
This is a PR to add a namespace to the `AuthorizeSessionRequest` to fix class declaration collisions in vault.
> fix: fix namespace in AuthorizeSessionRequest.cs

- .github/workflows/pull-request.yml
- .github/workflows/verify.yml
- scripts/checks/dotnetcheck.sh
- src/BasisTheory.net.Tests/Applications/CreateTests.cs
- src/BasisTheory.net.Tests/Applications/UpdateTests.cs
- src/BasisTheory.net.Tests/BasisTheory.net.Tests.csproj
- src/BasisTheory.net.Tests/Proxies/CreateTests.cs
- src/BasisTheory.net.Tests/Proxies/UpdateTests.cs
- src/BasisTheory.net.Tests/ReactorFormulas/CreateTests.cs
- src/BasisTheory.net.Tests/ReactorFormulas/UpdateTests.cs
- src/BasisTheory.net.Tests/Reactors/CreateTests.cs
- src/BasisTheory.net.Tests/Reactors/ReactTests.cs
- src/BasisTheory.net.Tests/Reactors/UpdateTests.cs
- src/BasisTheory.net.Tests/Tenants/UpdateTests.cs
- src/BasisTheory.net.Tests/Tokenize/TokenizeTests.cs
- src/BasisTheory.net.Tests/Tokens/CreateChildTests.cs
- src/BasisTheory.net.Tests/Tokens/CreateTests.cs
- src/BasisTheory.net.Tests/Tokens/UpdateTests.cs
- src/BasisTheory.net/Common/BaseClient.cs
- src/BasisTheory.net/Common/Requests/RequestOptions.cs
- src/BasisTheory.net/Common/Utilities/RuntimeInfoUtility.cs
> Eng 4186 add itempotency header

- .releaserc.json
- Fix build with dotnet pack breaking change when using -o option
> chore: fix build

- src/BasisTheory.net.Tests/Reactors/ReactTests.cs
- src/BasisTheory.net/Reactors/Requests/ReactRequest.cs
> feat: adding async reactor params

- src/BasisTheory.net.Tests/Proxies/Helpers/ProxyFactory.cs
- src/BasisTheory.net/Proxies/Entities/Proxy.cs
- adds ProxyHost property on Proxy model
> feat: adds ProxyHost property on Proxy model

- package.json
- src/BasisTheory.net.AspNetCore/BasisTheory.net.AspNetCore.csproj
- src/BasisTheory.net/BasisTheory.net.csproj
- yarn.lock
> fix: upgrading semantic release dependencies

- src/BasisTheory.net.Tests/Applications/CreateTests.cs
- src/BasisTheory.net.Tests/Applications/Helpers/ApplicationFactory.cs
- src/BasisTheory.net.Tests/Sessions/AuthorizeTests.cs
- src/BasisTheory.net.Tests/Sessions/Helpers/SessionFactory.cs
- src/BasisTheory.net/Applications/Entities/AccessRule.cs
- src/BasisTheory.net/Applications/Entities/Condition.cs
> feat: supporting conditions in access rules

- scripts/checks/dockercheck.sh
- src/BasisTheory.net.AspNetCore/BasisTheory.net.AspNetCore.csproj
- src/BasisTheory.net.Tests/BasisTheory.net.Tests.csproj
- src/BasisTheory.net.Tests/Helpers/BaseFixture.cs
- src/BasisTheory.net/BasisTheory.net.csproj
- Replaces Moq with NSubstitute
- Upgrades other deps
> chore: Replaces Moq with NSubstitute

- package.json
- src/BasisTheory.net.Tests/BasisTheory.net.Tests.csproj
- yarn.lock
> chore(deps): Upgrades dependencies

- src/BasisTheory.net.Tests/Reactors/Helpers/ReactorFactory.cs
- src/BasisTheory.net/ReactorFormulas/Entities/ReactorFormula.cs
- src/BasisTheory.net/Reactors/Entities/Reactor.cs
- feat: adds code to reactor and deprecates ReactorFormula
> feat: adds code to reactor and deprecates ReactorFormula

- src/BasisTheory.net.Tests/Proxies/Helpers/ProxyFactory.cs
- src/BasisTheory.net.Tests/Proxies/PatchTests.cs
- src/BasisTheory.net.Tests/Reactors/PatchTests.cs
- src/BasisTheory.net.Tests/Tokens/Helpers/TokenFactory.cs
- src/BasisTheory.net/Common/Errors/BasisTheoryError.cs
- src/BasisTheory.net/Proxies/ProxyClient.cs
- src/BasisTheory.net/Proxies/Requests/ProxyPatchRequest.cs
- src/BasisTheory.net/Reactors/ReactorClient.cs
- src/BasisTheory.net/Tokens/Requests/TokenCreateRequest.cs
- Supporting proxy and reactors patch
- Fixing issues
> feat: support patch proxies and reactors and some fixes

- .github/workflows/release.yml
- .releaserc.json
- src/BasisTheory.net.sln
- Fixing release workflow on windows runners
> fix(ci): Fixing release workflow on windows runners

- .github/workflows/release.yml
- fixing release workflow by changing back to linux runner and removing verify step
> chore(ci): fixing release workflow

- scripts/checks/dotnetcheck.sh
- src/BasisTheory.net.Tests/ThreeDS/AuthenticateTests.cs
- src/BasisTheory.net.Tests/ThreeDS/GetChallengeResultTests.cs
- src/BasisTheory.net.Tests/ThreeDS/GetSessionByIdTests.cs
- src/BasisTheory.net.Tests/ThreeDS/Helpers/ThreeDSFactory.cs
- src/BasisTheory.net.Tests/ThreeDS/Helpers/ThreeDSFixture.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSAcsRenderingType.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSAddress.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSAuthentication.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSCardholderAccountInfo.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSCardholderAuthenticationInfo.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSCardholderInfo.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSCardholderPhoneNumber.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSDeviceInfo.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSMerchantInfo.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSMerchantRiskInfo.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSMessageExtension.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSMethod.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSPriorAuthenticationInfo.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSPurchaseInfo.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSRequestorInfo.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSSession.cs
- src/BasisTheory.net/ThreeDS/Entities/ThreeDSVersion.cs
- src/BasisTheory.net/ThreeDS/Requests/AuthenticateThreeDSSessionRequest.cs
- src/BasisTheory.net/ThreeDS/ThreeDSClient.cs
> feat: add threeds endpoints

- src/BasisTheory.net.Tests/Tenants/Helpers/TenantFactory.cs
- src/BasisTheory.net/Tenants/Entities/Tenant.cs
> feat: add tenant type

- src/BasisTheory.net.Tests/Tenants/Helpers/TenantInvitationFactory.cs
- src/BasisTheory.net.Tests/Tenants/UpdateMemberTests.cs
- src/BasisTheory.net/Tenants/Entities/TenantInvitation.cs
- src/BasisTheory.net/Tenants/Requests/TenantMemberUpdateRequest.cs
- src/BasisTheory.net/Tenants/TenantClient.cs
- Adds `role` to Tenant Member Invitation
- Adds new `PUT` endpoint to update Tenant Members
> feat: Update SDK for invitations and tenant members

- .openapi-generator/templates/netcore_project.mustache
- .releaserc.json
- src/BasisTheory.net/BasisTheory.net.csproj
- Changed solution file location in `.releaserc.json`
- Removed unnecessary `README.md` csproj element that would cause `dotnet pack` to fail
> chore: Minor Fixes for release

- .github/workflows/release.yml
- Updating the github action dotnet version
> chore: Update dotnet release version

- README.md
- Encourage semantic versioning to increase the major version?
> BREAKING CHANGE: Increase major version

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- update workflows for new secrets mgmt
> chore: update workflows for new secrets
